version: "3"

networks:
  gitea:
    external: false

services:
  gitea_server:
    image: docker.io/gitea/gitea:latest
    env_file:
      - .env
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea-data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - gitea_db

  gitea_db:
    image: docker.io/pgvector/pgvector:pg16
    restart: always
    env_file:
      - .env
    networks:
      - gitea
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gitea_runner_act:
    image: docker.io/gitea/act_runner:latest
    restart: always
    env_file:
      - .env
      # - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
      # - GITEA_INSTANCE_URL=http://gitea_server:3000
    networks:
      - gitea
    depends_on:
      - gitea_server
    volumes:
      - ./runner-act-data/act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    
    
  # gitea_runner_dind:
  #   user: root
  #   build: 
  #     context: '.'
  #     dockerfile: Dockerfile.dind
  #   restart: always
  #   networks:
  #     - gitea
  #   privileged: true
  #   volumes:
  #     - ./dind-app:/app
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    # command: ["--host=unix:///var/run/docker.sock", "--container=gitea_runner_dind"]
    

  # gitea_runner_dind:
  #   image: docker.io/gitea/act_runner:latest-dind-rootless
  #   restart: always
  #   privileged: true
  #   depends_on:
  #     - gitea_server
  #   volumes:
  #     - ./runner-dind-data:/data
  #   environment:
  #     - GITEA_INSTANCE_URL=
  #     - DOCKER_HOST=unix:///var/run/user/1000/docker.sock
  #     # When using Docker Secrets, it's also possible to use
  #     # GITEA_RUNNER_REGISTRATION_TOKEN_FILE to pass the location.
  #     # The env var takes precedence.
  #     # Needed only for the first start.
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=
