# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    build:
      context: "."
      args:
        VIRTUAL_HOST: "pi.hole"
    network_mode: host
    hostname: ${VIRTUAL_HOST}
    dns: 
      - "127.0.0.1"
      - "1.1.1.1"
    env_file:
      - .env
    container_name: pihole_local
    image: docker.io/pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # ports:
    #   - "80:80/tcp"
    #   - "53:53/tcp"
    #   - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    # environment:
      # WEBPASSWORD: ${WEBPASSWORD}
      # VIRTUAL_HOST: "pi.hole"
      # FTLCONF_LOCAL_IPV4: "127.0.0.1"
    # Volumes store your data between container upgrades
    volumes:
      - './pihole-etc-data:/etc/pihole'
      - './pihole-etc-dnsmasq.d-data:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped


    