services:
  registry:
    image: docker.io/registry:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./docker-registry-data:/data