services:
  postgres_vector:
    image: docker.io/pgvector/pgvector:pg16
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: admin
      POSTGRES_DB: postgres_vector
    restart: unless-stopped
    ports:
      - '5432:5432'
  
  pgadmin:
    image: docker.io/dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      # PGADMIN_ENABLE_TLS: True
      # PGADMIN_LISTEN_PORT: 
      # PGADMIN_DEFAULT_PASSWORD_FILE: 
      # PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
      # PGADMIN_CONFIG_LOGIN_BANNER
      # PGADMIN_CONFIG_CONSOLE_LOG_LEVEL

    ports:
      - '5050:80'
