services:
  crowdsec:
    build:
      context: '.'
      dockerfile: Dockerfile

    restart: unless-stopped
    network_mode: host
    volumes:
      - ./app:/app
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /var/run/podman/podman.sock:/var/run/docker.sock
    env_file:
      - .env
    command: python3 -m http.server 80
